apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendcanary
spec:
  replicas: {{ .Values.canaryReplicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontendcanary
        image: 'theoafactor/simplewebapp:{{ .Values.canaryImage.tag }}'
        ports:
        - containerPort: 3000